### ISSUE TITLE
Missing docodile

### ISSUE THREAD

**Issue by jeromeku** [wandb/wandbot#19]
Interested in testing out the project but the [docodile](https://github.com/wandb/docodile) repo is missing in the [Data Ingestion](https://github.com/wandb/wandbot#data-ingestion) step.

**Comment by jeromeku** [comment]
FYI, resolved by manually generating docs per [docugen](https://github.com/wandb/docugen).

**Comment by 4722794** [comment]
Hey Jeromeku, how did you do it? 
I generated the docs and I now have a `ref` folder, but how did you generate the other files needed to run the app?
