### ISSUE TITLE
Default port from 8000 to 9000

### ISSUE THREAD

**Issue by ayulockin** [wandb/wandbot#32]
I think the default port used in this commend - `poetry run uvicorn wandbot.api.app:app --host="0.0.0.0" --port=8000 > api.log 2>&1)` might conflict with Jupyter Notebook's port.

Suggest to change it to 9000 maybe. 

Trivial issue though. :)

**Comment by parambharat** [comment]
@ayulockin , doesn't Jupyter default to 8888 or 8889 ? I mean there is no harm in changing the default port, but i'm curious that's all.

**Comment by morganmcg1** [comment]
closing this for now
